### ISSUE TITLE
测试精度问题

### ISSUE THREAD

**Issue by Laeglaur** [jiangxiluning/MASTER-TF#12]
您好，我使用您提供的weights，在IIIT5K数据集上测试，但Word Accuracy只有0.41，不知道是否有什么问题？

**Comment by jiangxiluning** [comment]
https://github.com/jiangxiluning/MASTER-TF/commit/85f9217af8697e41aefe5121e580efa0d6d04d92
你试下这个版本的代码， 0.41 肯定有问题，有改什么代码么。

**Comment by Laeglaur** [comment]
我没有修改代码，只是测试，weights也是从google driver这个版本下载的。
这是一些测试中错误的结果，格式为[label -> pred]，看起来可能的确是weights的问题，存在一些误识别
```
private -> pravate
salutes -> dallukes
dolce -> dole
gabbana -> gabbaina
kingfisher -> kagger
clear -> cleak
channel -> chakkkink
loan -> lodd
that -> thah
home -> homen
jammu -> jamm
41km -> kikm
83km -> 8kki
visit -> visi
again -> agalin
state -> jikele
bank -> bak
india -> indiv
sbi -> sbl
platinum -> plamkkm
4865 -> higgse
4567 -> hgbi
1212 -> 1171k
05 -> ob
state -> sja
of -> k

```

**Comment by jiangxiluning** [comment]
@Laeglaur 你试试我给你commit 的版本代码，因为最新的代码 backbone 有修改，需要重新训练。

**Comment by Laeglaur** [comment]
您好，您给我的commit中好像只修改了ReadMe，增加了google driver的链接。

**Comment by Laeglaur** [comment]
嗯嗯可以了，谢谢~ 应该就是修改了` layers.append(block(planes, gcb_config=gcb_config, use_gcb=use_gcb))` 的问题

**Comment by jiangxiluning** [comment]
@Laeglaur 权重不对应，推理精度会有问题
