### ISSUE TITLE
请问这个模型对长文本的识别和CRNN比较，哪个效果好？

### ISSUE THREAD

**Issue by LanWong1** [jiangxiluning/MASTER-TF#2]
之前看文章说基于attention的对长文本文字识别没有crnn效果好，针对文档类，非自然场景文字。不知道这个模型如何？

**Comment by jiangxiluning** [comment]
非常长的文本行，我们也没有测试，100 -200 应该没问题。

LanWong1 <notifications@github.com> 于2020年7月30日周四 下午5:26写道：
