### ISSUE TITLE
 Hello, when I initialized the model, I only saw the decoder, not the GCAttention part

### ISSUE THREAD

**Issue by Waynepoo** [jiangxiluning/MASTER-TF#4]
![image](https://user-images.githubusercontent.com/41176549/89387976-e4cb7900-d735-11ea-912b-8d91ee9e026c.png)

Can you help me explain

**Comment by jiangxiluning** [comment]
GCAttention is integrated in ResNet 31.

**Comment by Waynepoo** [comment]
> GCAttention is integrated in ResNet 31.

thank
