### ISSUE TITLE
pytorch implementation

### ISSUE THREAD

**Issue by CuongNN218** [jiangxiluning/MASTER-TF#9]
where can I find your pytorch implementation ?

**Comment by cuong12ly1** [comment]
@jiangxiluning I want to use test time augmentation, how can I find it in your code ?

**Comment by wenwenyu** [comment]
Hi, @cuong12ly1, thank you for your interest in our work.  For now, the pytorch implementation hasn't released, waiting for the submission notification of the paper. In the future, we will think about it.

**Comment by CuongNN218** [comment]
@wenwenyu can you share your pytorch code for me ?

**Comment by wenwenyu** [comment]
@CuongNN218 Hi, thanks for your attention. The code will be coming soon. stay tuned.

**Comment by CuongNN218** [comment]
@wenwenyu i has been waiting since October but still waiting :v

**Comment by wenwenyu** [comment]
@CuongNN218 Sorry for that. We also wait for the submission notification of the paper. Once we have the results of our paper, we will prepare the code. Patience is all you need. (:

**Comment by jiangxiluning** [comment]
@CuongNN218 I think you won't wait a long time anymore.

**Comment by wenwenyu** [comment]
@CuongNN218 Hi, we have released pytorch code at [MASTER-pytorch](https://github.com/wenwenyu/MASTER-pytorch).
